# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    permissions:
        pull-requests: write
        contents: read
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install tools
      run: dotnet tool install -g dotnet-fsharplint

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test For C# app
      run: dotnet test --filter FullyQualifiedName~app.Test.Unit --no-build --verbosity normal

    - name: Unit Test For F# engine
      run: dotnet test --filter FullyQualifiedName~engine.Test --no-build --verbosity normal

    - name: Functional tests
      run: dotnet test --filter FullyQualifiedName~app.Test.Functional --no-build --verbosity normal